In [3]:
import pandas as pd

In [4]:
df=pd.DataFrame({
    "Order Date":[
        "2024-01-10",
        "2024-01-15",
        "2024-02-05",
        "2024-02-12",
        "2024-03-01",
        "2024-03-15",
        "2024-04-10",
        "2024-04-20",
        "2024-05-05",
        "2024-01-15"
    ],
    "Product name":[
        "Laptop",
        "Mouse",
        "Printer",
        "Tablet",
        "Laptop",
        "Monitor",
        "Mouse",
        "Printer",
        "Smartwatch",
        "Mouse"
    ],
    "Category":[
        "Electronics",
        "Accessories",
        "Office",
        "Electronics",
        "Electronics",
        "Accessories",
        "Accessories",
        "Office",
        "Electronics",
        "Accessories"
    ],
    "Region":[
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South"
    ],
    "Quantity":[
        2,
        5,
        3,
        4,
        1,
        2,
        6,
        2,
        3,
        5
    ],
    "Sales":[
        50000,
        2500,
        9000,
        30000,
        55000,
        16000,
        3000,
        6000,
        45000,
        2500
    ],
    "Profit":[
        10000,
        500,
        1500,
        6000,
        11000,
        3000,
        None,
        1000,
        9000,
        500
    ]
})

In [5]:
print("Original Dataset")
print("-"*50)
display(df)

Original Dataset
--------------------------------------------------

   Order Date Product name     Category Region  Quantity  Sales   Profit
0  2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0
2  2024-02-05      Printer       Office   East         3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North         1  55000  11000.0
5  2024-03-15      Monitor  Accessories  South         2  16000   3000.0
6  2024-04-10        Mouse  Accessories   East         6   3000      NaN
7  2024-04-20      Printer       Office   West         2   6000   1000.0
8  2024-05-05   Smartwatch  Electronics  North         3  45000   9000.0
9  2024-01-15        Mouse  Accessories  South         5   2500    500.0

In [6]:
print("First five records")
print("-"*50)
display(df.head())

First five records
--------------------------------------------------

   Order Date Product name     Category Region  Quantity  Sales   Profit
0  2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0
2  2024-02-05      Printer       Office   East         3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North         1  55000  11000.0

In [8]:
print("First five records")
print("-"*50)
display(df.tail())

First five records
--------------------------------------------------

   Order Date Product name     Category Region  Quantity  Sales  Profit
5  2024-03-15      Monitor  Accessories  South         2  16000  3000.0
6  2024-04-10        Mouse  Accessories   East         6   3000     NaN
7  2024-04-20      Printer       Office   West         2   6000  1000.0
8  2024-05-05   Smartwatch  Electronics  North         3  45000  9000.0
9  2024-01-15        Mouse  Accessories  South         5   2500   500.0

In [9]:
print("First five records")
print("-"*50)
display(df.head(2))

First five records
--------------------------------------------------

   Order Date Product name     Category Region  Quantity  Sales   Profit
0  2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0

In [12]:
print("Dataset Shape")
print("-"*50)
print(df.shape)

Dataset Shape
--------------------------------------------------
(10, 7)

In [11]:
print("Column names")
print("-"*50)
print(df.columns)

Column names
--------------------------------------------------
Index(['Order Date', 'Product name', 'Category', 'Region', 'Quantity', 'Sales',
       'Profit'],
      dtype='object')

In [13]:
print("Data Types")
print("-"*50)
print(df.dtypes)

Data Types
--------------------------------------------------
Order Date       object
Product name     object
Category         object
Region           object
Quantity          int64
Sales             int64
Profit          float64
dtype: object

In [14]:
print("Descriptive statistics")
print("-"*50)
print(df.describe())

Descriptive statistics
--------------------------------------------------
        Quantity         Sales        Profit
count  10.000000     10.000000      9.000000
mean    3.300000  21900.000000   4722.222222
std     1.636392  21209.012759   4330.928820
min     1.000000   2500.000000    500.000000
25%     2.000000   3750.000000   1000.000000
50%     3.000000  12500.000000   3000.000000
75%     4.750000  41250.000000   9000.000000
max     6.000000  55000.000000  11000.000000

In [15]:
print("Missing values")
print("-"*50)
print(df.isnull().sum())

Missing values
--------------------------------------------------
Order Date      0
Product name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          1
dtype: int64

In [16]:
print("Rows containing missing values")
print("-"*50)
display(df[df.isnull().any(axis=1)])

Rows containing missing values
--------------------------------------------------

   Order Date Product name     Category Region  Quantity  Sales  Profit
6  2024-04-10        Mouse  Accessories   East         6   3000     NaN

In [17]:
print("Duplicate Record")
print("-"*50)
print(df.duplicated().sum())

Duplicate Record
--------------------------------------------------
1

In [18]:
print("Duplicate Record")
print("-"*50)
print(df[df.duplicated()])

Duplicate Record
--------------------------------------------------
   Order Date Product name     Category Region  Quantity  Sales  Profit
9  2024-01-15        Mouse  Accessories  South         5   2500   500.0

In [24]:
print("Concatenation")
print("-"*50)
new_sales=pd.DataFrame({
"Order Date": 
[
      "2024-06-01",
      "2024-06-05",
      "2024-06-10"
],
"Product name":
[
    "Laptop",
    "Mouse",
    "Printer"
],
"Category":[
    "Electronics",
    "Accessories",
    "Office"
],
"Region":
[
    "North",
    "South",
    "East"
],
"Quantity":
[
    2,
    4,
    3
],
"Sales":
[
    60000,
    2000,
    9000
],
"Profit":
[
    12000,
    400,
    1800
]
})

Concatenation
--------------------------------------------------

In [25]:
print("New sales Dataframe")
display(new_sales)

New sales Dataframe

   Order Date Product name     Category Region  Quantity  Sales  Profit
0  2024-06-01       Laptop  Electronics  North         2  60000   12000
1  2024-06-05        Mouse  Accessories  South         4   2000     400
2  2024-06-10      Printer       Office   East         3   9000    1800

In [26]:
combined_df=pd.concat(
    [df,new_sales],
    ignore_index=True
)

In [27]:
print("Concatenated frame")
print("-"*50)
print(combined_df)

Concatenated frame
--------------------------------------------------
    Order Date Product name     Category Region  Quantity  Sales   Profit
0   2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1   2024-01-15        Mouse  Accessories  South         5   2500    500.0
2   2024-02-05      Printer       Office   East         3   9000   1500.0
3   2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4   2024-03-01       Laptop  Electronics  North         1  55000  11000.0
5   2024-03-15      Monitor  Accessories  South         2  16000   3000.0
6   2024-04-10        Mouse  Accessories   East         6   3000      NaN
7   2024-04-20      Printer       Office   West         2   6000   1000.0
8   2024-05-05   Smartwatch  Electronics  North         3  45000   9000.0
9   2024-01-15        Mouse  Accessories  South         5   2500    500.0
10  2024-06-01       Laptop  Electronics  North         2  60000  12000.0
11  2024-06-05        Mouse  Accessories  South         4   2000    400.0
12  2024-06-10      Printer       Office   East         3   9000   1800.0

In [31]:
product_info=pd.DataFrame({
    "Product name":[
        "Laptop",
        "Mouse",
        "Printer",
        "Tablet",
        "Monitor"
    ],
    "Supplier":
    [
        "Dell",
        "Logitech",
        "HP",
        "Samsung",
        "LG"
    ],
    "Discount":
    [
        10,
        5,
        15,
        8,
        2
    ]
})

In [32]:
display(product_info)

  Product name  Supplier  Discount
0       Laptop      Dell        10
1        Mouse  Logitech         5
2      Printer        HP        15
3       Tablet   Samsung         8
4      Monitor        LG         2

In [33]:
merged_df=pd.merge(
    df,
    product_info,
    on="Product name",
    how="left"
)
print(merged_df)

   Order Date Product name     Category Region  Quantity  Sales   Profit  \
0  2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0
2  2024-02-05      Printer       Office   East         3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North         1  55000  11000.0
5  2024-03-15      Monitor  Accessories  South         2  16000   3000.0
6  2024-04-10        Mouse  Accessories   East         6   3000      NaN
7  2024-04-20      Printer       Office   West         2   6000   1000.0
8  2024-05-05   Smartwatch  Electronics  North         3  45000   9000.0
9  2024-01-15        Mouse  Accessories  South         5   2500    500.0

   Supplier  Discount
0      Dell      10.0
1  Logitech       5.0
2        HP      15.0
3   Samsung       8.0
4      Dell      10.0
5        LG       2.0
6  Logitech       5.0
7        HP      15.0
8       NaN       NaN
9  Logitech       5.0

In [38]:
region_info=pd.DataFrame({
    "Region_Manager":
    [
        "Manager A",
        "Manager B",
        "Manager C",
        "Manager D"
    ],
    "Region":
    [
    "North",
    "South",
    "East",
    "West"
    ]
        })

In [40]:
df_region=df.set_index("Region")
joined_df=df_region.join(region_info)
print(joined_df)

        Order Date Product name     Category  Quantity  Sales   Profit  \
Region
North   2024-01-10       Laptop  Electronics         2  50000  10000.0
South   2024-01-15        Mouse  Accessories         5   2500    500.0
East    2024-02-05      Printer       Office         3   9000   1500.0
West    2024-02-12       Tablet  Electronics         4  30000   6000.0
North   2024-03-01       Laptop  Electronics         1  55000  11000.0
South   2024-03-15      Monitor  Accessories         2  16000   3000.0
East    2024-04-10        Mouse  Accessories         6   3000      NaN
West    2024-04-20      Printer       Office         2   6000   1000.0
North   2024-05-05   Smartwatch  Electronics         3  45000   9000.0
South   2024-01-15        Mouse  Accessories         5   2500    500.0

       Region_Manager Region
Region
North             NaN    NaN
South             NaN    NaN
East              NaN    NaN
West              NaN    NaN
North             NaN    NaN
South             NaN    NaN
East              NaN    NaN
West              NaN    NaN
North             NaN    NaN
South             NaN    NaN

In [41]:
region_sales=df.groupby(
    "Region"
)["Sales"].sum()
print("Total sales by region")
display(region_sales)

Total sales by region

Region
East      12000
North    150000
South     21000
West      36000
Name: Sales, dtype: int64

In [42]:
pivot_table=pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    columns="Region",
    aggfunc="sum",
    fill_value=0
)

In [44]:
print('Pivot table is\n',pivot_table)

Pivot table is
 Region       East   North  South   West
Category
Accessories  3000       0  21000      0
Electronics     0  150000      0  30000
Office       9000       0      0   6000